"""Tests for portname wireplumber module."""

import os
import shutil
import tempfile
import unittest
from unittest.mock import patch

import portname.wireplumber as wp


class TestSafeFilename(unittest.TestCase):
    def test_simple_name(self):
        self.assertEqual(wp._safe_filename("alsa_output.usb-Device-00"), "alsa_output_usb-Device-00")

    def test_special_chars(self):
        self.assertEqual(wp._safe_filename("name with spaces!"), "name_with_spaces_")

    def test_alphanumeric_preserved(self):
        self.assertEqual(wp._safe_filename("abc-123_DEF"), "abc-123_DEF")


class TestGenerateRule(unittest.TestCase):
    def test_generates_valid_config(self):
        content = wp.generate_rule("alsa_output.usb-MyDevice-00.analog-stereo", "My USB Headset")
        self.assertIn("monitor.alsa.rules", content)
        self.assertIn('node.name = "alsa_output.usb-MyDevice-00.analog-stereo"', content)
        self.assertIn('node.description = "My USB Headset"', content)
        self.assertIn('node.nick        = "My USB Headset"', content)
        self.assertIn("# Generated by portname", content)

    def test_escapes_quotes(self):
        content = wp.generate_rule("node", 'My "Special" Device')
        self.assertIn('node.description = "My \\"Special\\" Device"', content)

    def test_escapes_backslashes(self):
        content = wp.generate_rule("node", "path\\to\\thing")
        self.assertIn('node.description = "path\\\\to\\\\thing"', content)


class TestRenameNode(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self._orig_dir = wp.WIREPLUMBER_DIR
        wp.WIREPLUMBER_DIR = self.tmpdir

    def tearDown(self):
        wp.WIREPLUMBER_DIR = self._orig_dir
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    @patch("os.geteuid", return_value=0)
    def test_creates_config_file(self, mock_euid):
        wp.rename_node("alsa_output.usb-Test-00.stereo", "My Device")

        # Config file should exist
        expected_path = os.path.join(
            self.tmpdir, "90-portname-alsa_output_usb-Test-00_stereo.conf"
        )
        self.assertTrue(os.path.exists(expected_path))

        with open(expected_path) as f:
            content = f.read()
        self.assertIn('node.name = "alsa_output.usb-Test-00.stereo"', content)
        self.assertIn('node.description = "My Device"', content)

    @patch("os.geteuid", return_value=0)
    def test_creates_directory_if_missing(self, mock_euid):
        wp.WIREPLUMBER_DIR = os.path.join(self.tmpdir, "subdir", "wireplumber")
        wp.rename_node("alsa_output.usb-Test-00", "Test")
        self.assertTrue(os.path.isdir(wp.WIREPLUMBER_DIR))

    @patch("os.geteuid", return_value=1000)
    def test_requires_root(self, mock_euid):
        with self.assertRaises(PermissionError):
            wp.rename_node("node", "name")


class TestRevertNode(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self._orig_dir = wp.WIREPLUMBER_DIR
        wp.WIREPLUMBER_DIR = self.tmpdir

    def tearDown(self):
        wp.WIREPLUMBER_DIR = self._orig_dir
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    @patch("os.geteuid", return_value=0)
    def test_removes_config_file(self, mock_euid):
        # Create a config file first
        wp.rename_node("alsa_output.usb-Test-00.stereo", "My Device")
        config_path = wp._config_path("alsa_output.usb-Test-00.stereo")
        self.assertTrue(os.path.exists(config_path))

        # Revert should remove it
        wp.revert_node("alsa_output.usb-Test-00.stereo")
        self.assertFalse(os.path.exists(config_path))

    @patch("os.geteuid", return_value=0)
    def test_revert_not_renamed_raises(self, mock_euid):
        with self.assertRaises(ValueError):
            wp.revert_node("nonexistent-node")

    @patch("os.geteuid", return_value=1000)
    def test_requires_root(self, mock_euid):
        with self.assertRaises(PermissionError):
            wp.revert_node("node")


class TestIsNodeRenamed(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self._orig_dir = wp.WIREPLUMBER_DIR
        wp.WIREPLUMBER_DIR = self.tmpdir

    def tearDown(self):
        wp.WIREPLUMBER_DIR = self._orig_dir
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    @patch("os.geteuid", return_value=0)
    def test_returns_true_when_renamed(self, mock_euid):
        wp.rename_node("alsa_output.usb-Test-00", "Test")
        self.assertTrue(wp.is_node_renamed("alsa_output.usb-Test-00"))

    def test_returns_false_when_not_renamed(self):
        self.assertFalse(wp.is_node_renamed("nonexistent-node"))


class TestGetCurrentDescription(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self._orig_dir = wp.WIREPLUMBER_DIR
        wp.WIREPLUMBER_DIR = self.tmpdir

    def tearDown(self):
        wp.WIREPLUMBER_DIR = self._orig_dir
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    @patch("os.geteuid", return_value=0)
    def test_reads_description(self, mock_euid):
        wp.rename_node("alsa_output.usb-Test-00", "My Custom Name")
        desc = wp.get_current_description("alsa_output.usb-Test-00")
        self.assertEqual(desc, "My Custom Name")

    def test_returns_none_when_not_renamed(self):
        self.assertIsNone(wp.get_current_description("nonexistent"))


class TestGetAllRenamed(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self._orig_dir = wp.WIREPLUMBER_DIR
        wp.WIREPLUMBER_DIR = self.tmpdir

    def tearDown(self):
        wp.WIREPLUMBER_DIR = self._orig_dir
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    @patch("os.geteuid", return_value=0)
    def test_lists_all_renamed(self, mock_euid):
        wp.rename_node("alsa_output.usb-A-00", "Device A")
        wp.rename_node("alsa_output.usb-B-00", "Device B")

        renamed = wp.get_all_renamed()
        names = [n for n, d in renamed]
        descs = [d for n, d in renamed]

        self.assertIn("alsa_output.usb-A-00", names)
        self.assertIn("alsa_output.usb-B-00", names)
        self.assertIn("Device A", descs)
        self.assertIn("Device B", descs)

    def test_empty_when_no_renames(self):
        self.assertEqual(wp.get_all_renamed(), [])

    def test_ignores_non_portname_files(self):
        # Create a file that doesn't match our prefix
        with open(os.path.join(self.tmpdir, "50-other-config.conf"), "w") as f:
            f.write("some config")
        self.assertEqual(wp.get_all_renamed(), [])


class TestValidateNodeName(unittest.TestCase):
    def test_valid_node_name(self):
        self.assertEqual(
            wp.validate_node_name("alsa_output.usb-Device-00.analog-stereo"),
            "alsa_output.usb-Device-00.analog-stereo",
        )

    def test_empty_raises(self):
        with self.assertRaises(ValueError):
            wp.validate_node_name("")

    def test_whitespace_only_raises(self):
        with self.assertRaises(ValueError):
            wp.validate_node_name("   ")

    def test_newline_rejected(self):
        with self.assertRaises(ValueError):
            wp.validate_node_name("node\ninjection")

    def test_slash_rejected(self):
        with self.assertRaises(ValueError):
            wp.validate_node_name("../../etc/passwd")

    def test_space_rejected(self):
        with self.assertRaises(ValueError):
            wp.validate_node_name("node with spaces")

    def test_too_long_rejected(self):
        with self.assertRaises(ValueError):
            wp.validate_node_name("a" * 257)

    def test_max_length_ok(self):
        name = "a" * 256
        self.assertEqual(wp.validate_node_name(name), name)

    def test_colon_and_plus_allowed(self):
        self.assertEqual(wp.validate_node_name("node:name+extra"), "node:name+extra")

    def test_strips_whitespace(self):
        self.assertEqual(
            wp.validate_node_name("  alsa_output.usb-Test-00  "),
            "alsa_output.usb-Test-00",
        )


class TestEscapeSpaJson(unittest.TestCase):
    def test_strips_newlines(self):
        result = wp._escape_spa_json('before\nafter')
        self.assertNotIn("\n", result)
        self.assertEqual(result, "beforeafter")

    def test_strips_carriage_return(self):
        result = wp._escape_spa_json('before\rafter')
        self.assertNotIn("\r", result)

    def test_strips_null_bytes(self):
        result = wp._escape_spa_json('before\x00after')
        self.assertNotIn("\x00", result)

    def test_strips_tabs(self):
        result = wp._escape_spa_json('before\tafter')
        self.assertNotIn("\t", result)

    def test_escapes_quotes_and_backslashes(self):
        result = wp._escape_spa_json('say "hello" \\ world')
        self.assertEqual(result, 'say \\"hello\\" \\\\ world')


class TestSafeWrite(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()

    def tearDown(self):
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_writes_file(self):
        path = os.path.join(self.tmpdir, "test.conf")
        wp._safe_write(path, "hello world")
        with open(path) as f:
            self.assertEqual(f.read(), "hello world")

    def test_sets_permissions(self):
        path = os.path.join(self.tmpdir, "test.conf")
        wp._safe_write(path, "content")
        mode = os.stat(path).st_mode & 0o777
        self.assertEqual(mode, 0o644)

    def test_refuses_symlink(self):
        target = os.path.join(self.tmpdir, "target.txt")
        with open(target, "w") as f:
            f.write("original")
        link = os.path.join(self.tmpdir, "link.conf")
        os.symlink(target, link)

        with self.assertRaises(RuntimeError) as ctx:
            wp._safe_write(link, "overwritten")
        self.assertIn("symlink", str(ctx.exception))
        # Target file should be untouched
        with open(target) as f:
            self.assertEqual(f.read(), "original")


class TestSafeRemove(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()

    def tearDown(self):
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_removes_regular_file(self):
        path = os.path.join(self.tmpdir, "test.conf")
        with open(path, "w") as f:
            f.write("content")
        wp._safe_remove(path)
        self.assertFalse(os.path.exists(path))

    def test_refuses_symlink(self):
        target = os.path.join(self.tmpdir, "target.txt")
        with open(target, "w") as f:
            f.write("important")
        link = os.path.join(self.tmpdir, "link.conf")
        os.symlink(target, link)

        with self.assertRaises(RuntimeError) as ctx:
            wp._safe_remove(link)
        self.assertIn("symlink", str(ctx.exception))
        # Target should still exist
        self.assertTrue(os.path.exists(target))

    def test_raises_on_nonexistent(self):
        with self.assertRaises(ValueError):
            wp._safe_remove(os.path.join(self.tmpdir, "nope"))


class TestGetAllRenamedSkipsSymlinks(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self._orig_dir = wp.WIREPLUMBER_DIR
        wp.WIREPLUMBER_DIR = self.tmpdir

    def tearDown(self):
        wp.WIREPLUMBER_DIR = self._orig_dir
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    def test_skips_symlinked_config_files(self):
        # Create a real config file
        real_path = os.path.join(self.tmpdir, "real.conf")
        with open(real_path, "w") as f:
            f.write('node.name = "real"\nnode.description = "Real"')

        # Create a symlink with our prefix
        link_path = os.path.join(self.tmpdir, "90-portname-evil.conf")
        os.symlink(real_path, link_path)

        renamed = wp.get_all_renamed()
        # Symlink should be skipped
        self.assertEqual(renamed, [])


class TestRevertAll(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self._orig_dir = wp.WIREPLUMBER_DIR
        wp.WIREPLUMBER_DIR = self.tmpdir

    def tearDown(self):
        wp.WIREPLUMBER_DIR = self._orig_dir
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    @patch("os.geteuid", return_value=0)
    def test_reverts_all(self, mock_euid):
        wp.rename_node("alsa_output.usb-A-00", "Device A")
        wp.rename_node("alsa_output.usb-B-00", "Device B")

        reverted = wp.revert_all()

        self.assertEqual(len(reverted), 2)
        self.assertFalse(wp.is_node_renamed("alsa_output.usb-A-00"))
        self.assertFalse(wp.is_node_renamed("alsa_output.usb-B-00"))

    @patch("os.geteuid", return_value=0)
    def test_revert_all_empty(self, mock_euid):
        reverted = wp.revert_all()
        self.assertEqual(reverted, [])

    @patch("os.geteuid", return_value=0)
    def test_continues_past_failures(self, mock_euid):
        """If one revert fails, the rest should still be attempted."""
        wp.rename_node("alsa_output.usb-A-00", "Device A")
        wp.rename_node("alsa_output.usb-B-00", "Device B")

        # Make A's config a symlink (will fail _safe_remove) but B is fine
        a_path = wp._config_path("alsa_output.usb-A-00")
        b_path = wp._config_path("alsa_output.usb-B-00")

        # Replace A's config with a symlink to a temp file
        dummy = os.path.join(self.tmpdir, "dummy")
        with open(dummy, "w") as f:
            f.write("x")
        os.remove(a_path)
        os.symlink(dummy, a_path)

        # revert_all should succeed for B even though A fails
        reverted = wp.revert_all()
        self.assertIn("alsa_output.usb-B-00", reverted)
        self.assertNotIn("alsa_output.usb-A-00", reverted)
        self.assertFalse(os.path.exists(b_path))

    @patch("os.geteuid", return_value=1000)
    def test_requires_root(self, mock_euid):
        with self.assertRaises(PermissionError):
            wp.revert_all()


if __name__ == "__main__":
    unittest.main()
