"""Tests for portname wireplumber module."""

import os
import shutil
import tempfile
import unittest
from unittest.mock import patch

import portname.wireplumber as wp


class TestSafeFilename(unittest.TestCase):
    def test_simple_name(self):
        self.assertEqual(wp._safe_filename("alsa_output.usb-Device-00"), "alsa_output_usb-Device-00")

    def test_special_chars(self):
        self.assertEqual(wp._safe_filename("name with spaces!"), "name_with_spaces_")

    def test_alphanumeric_preserved(self):
        self.assertEqual(wp._safe_filename("abc-123_DEF"), "abc-123_DEF")


class TestGenerateRule(unittest.TestCase):
    def test_generates_valid_config(self):
        content = wp.generate_rule("alsa_output.usb-MyDevice-00.analog-stereo", "My USB Headset")
        self.assertIn("monitor.alsa.rules", content)
        self.assertIn('node.name = "alsa_output.usb-MyDevice-00.analog-stereo"', content)
        self.assertIn('node.description = "My USB Headset"', content)
        self.assertIn('node.nick        = "My USB Headset"', content)
        self.assertIn("# Generated by portname", content)

    def test_escapes_quotes(self):
        content = wp.generate_rule("node", 'My "Special" Device')
        self.assertIn('node.description = "My \\"Special\\" Device"', content)

    def test_escapes_backslashes(self):
        content = wp.generate_rule("node", "path\\to\\thing")
        self.assertIn('node.description = "path\\\\to\\\\thing"', content)


class TestRenameNode(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self._orig_dir = wp.WIREPLUMBER_DIR
        wp.WIREPLUMBER_DIR = self.tmpdir

    def tearDown(self):
        wp.WIREPLUMBER_DIR = self._orig_dir
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    @patch("os.geteuid", return_value=0)
    def test_creates_config_file(self, mock_euid):
        wp.rename_node("alsa_output.usb-Test-00.stereo", "My Device")

        # Config file should exist
        expected_path = os.path.join(
            self.tmpdir, "90-portname-alsa_output_usb-Test-00_stereo.conf"
        )
        self.assertTrue(os.path.exists(expected_path))

        with open(expected_path) as f:
            content = f.read()
        self.assertIn('node.name = "alsa_output.usb-Test-00.stereo"', content)
        self.assertIn('node.description = "My Device"', content)

    @patch("os.geteuid", return_value=0)
    def test_creates_directory_if_missing(self, mock_euid):
        wp.WIREPLUMBER_DIR = os.path.join(self.tmpdir, "subdir", "wireplumber")
        wp.rename_node("alsa_output.usb-Test-00", "Test")
        self.assertTrue(os.path.isdir(wp.WIREPLUMBER_DIR))

    @patch("os.geteuid", return_value=1000)
    def test_requires_root(self, mock_euid):
        with self.assertRaises(PermissionError):
            wp.rename_node("node", "name")


class TestRevertNode(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self._orig_dir = wp.WIREPLUMBER_DIR
        wp.WIREPLUMBER_DIR = self.tmpdir

    def tearDown(self):
        wp.WIREPLUMBER_DIR = self._orig_dir
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    @patch("os.geteuid", return_value=0)
    def test_removes_config_file(self, mock_euid):
        # Create a config file first
        wp.rename_node("alsa_output.usb-Test-00.stereo", "My Device")
        config_path = wp._config_path("alsa_output.usb-Test-00.stereo")
        self.assertTrue(os.path.exists(config_path))

        # Revert should remove it
        wp.revert_node("alsa_output.usb-Test-00.stereo")
        self.assertFalse(os.path.exists(config_path))

    @patch("os.geteuid", return_value=0)
    def test_revert_not_renamed_raises(self, mock_euid):
        with self.assertRaises(ValueError):
            wp.revert_node("nonexistent-node")

    @patch("os.geteuid", return_value=1000)
    def test_requires_root(self, mock_euid):
        with self.assertRaises(PermissionError):
            wp.revert_node("node")


class TestIsNodeRenamed(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self._orig_dir = wp.WIREPLUMBER_DIR
        wp.WIREPLUMBER_DIR = self.tmpdir

    def tearDown(self):
        wp.WIREPLUMBER_DIR = self._orig_dir
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    @patch("os.geteuid", return_value=0)
    def test_returns_true_when_renamed(self, mock_euid):
        wp.rename_node("alsa_output.usb-Test-00", "Test")
        self.assertTrue(wp.is_node_renamed("alsa_output.usb-Test-00"))

    def test_returns_false_when_not_renamed(self):
        self.assertFalse(wp.is_node_renamed("nonexistent-node"))


class TestGetCurrentDescription(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self._orig_dir = wp.WIREPLUMBER_DIR
        wp.WIREPLUMBER_DIR = self.tmpdir

    def tearDown(self):
        wp.WIREPLUMBER_DIR = self._orig_dir
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    @patch("os.geteuid", return_value=0)
    def test_reads_description(self, mock_euid):
        wp.rename_node("alsa_output.usb-Test-00", "My Custom Name")
        desc = wp.get_current_description("alsa_output.usb-Test-00")
        self.assertEqual(desc, "My Custom Name")

    def test_returns_none_when_not_renamed(self):
        self.assertIsNone(wp.get_current_description("nonexistent"))


class TestGetAllRenamed(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self._orig_dir = wp.WIREPLUMBER_DIR
        wp.WIREPLUMBER_DIR = self.tmpdir

    def tearDown(self):
        wp.WIREPLUMBER_DIR = self._orig_dir
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    @patch("os.geteuid", return_value=0)
    def test_lists_all_renamed(self, mock_euid):
        wp.rename_node("alsa_output.usb-A-00", "Device A")
        wp.rename_node("alsa_output.usb-B-00", "Device B")

        renamed = wp.get_all_renamed()
        names = [n for n, d in renamed]
        descs = [d for n, d in renamed]

        self.assertIn("alsa_output.usb-A-00", names)
        self.assertIn("alsa_output.usb-B-00", names)
        self.assertIn("Device A", descs)
        self.assertIn("Device B", descs)

    def test_empty_when_no_renames(self):
        self.assertEqual(wp.get_all_renamed(), [])

    def test_ignores_non_portname_files(self):
        # Create a file that doesn't match our prefix
        with open(os.path.join(self.tmpdir, "50-other-config.conf"), "w") as f:
            f.write("some config")
        self.assertEqual(wp.get_all_renamed(), [])


class TestRevertAll(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.mkdtemp()
        self._orig_dir = wp.WIREPLUMBER_DIR
        wp.WIREPLUMBER_DIR = self.tmpdir

    def tearDown(self):
        wp.WIREPLUMBER_DIR = self._orig_dir
        shutil.rmtree(self.tmpdir, ignore_errors=True)

    @patch("os.geteuid", return_value=0)
    def test_reverts_all(self, mock_euid):
        wp.rename_node("alsa_output.usb-A-00", "Device A")
        wp.rename_node("alsa_output.usb-B-00", "Device B")

        reverted = wp.revert_all()

        self.assertEqual(len(reverted), 2)
        self.assertFalse(wp.is_node_renamed("alsa_output.usb-A-00"))
        self.assertFalse(wp.is_node_renamed("alsa_output.usb-B-00"))

    @patch("os.geteuid", return_value=0)
    def test_revert_all_empty(self, mock_euid):
        reverted = wp.revert_all()
        self.assertEqual(reverted, [])

    @patch("os.geteuid", return_value=1000)
    def test_requires_root(self, mock_euid):
        with self.assertRaises(PermissionError):
            wp.revert_all()


if __name__ == "__main__":
    unittest.main()
