"""WirePlumber rule generation for renaming USB audio devices/nodes."""

import logging
import os
import re
import stat

log = logging.getLogger(__name__)

_DEFAULT_WIREPLUMBER_DIR = "/etc/wireplumber/wireplumber.conf.d"

# Allow override for testing, but ignore when running as root (same pattern as core.py).
if os.geteuid() == 0:
    WIREPLUMBER_DIR = _DEFAULT_WIREPLUMBER_DIR
else:
    WIREPLUMBER_DIR = os.environ.get(
        "PORTNAME_WIREPLUMBER_DIR", _DEFAULT_WIREPLUMBER_DIR
    )

# Prefix for config files created by portname
_FILE_PREFIX = "90-portname-"

# Node names: alphanumeric, dots, dashes, underscores, colons (PipeWire convention)
_VALID_NODE_NAME_RE = re.compile(r"^[a-zA-Z0-9._:+-]{1,256}$")


def validate_node_name(node_name):
    """Validate a PipeWire node name. Raises ValueError if invalid."""
    if not node_name or not node_name.strip():
        raise ValueError("Node name cannot be empty")
    node_name = node_name.strip()
    if not _VALID_NODE_NAME_RE.match(node_name):
        raise ValueError(
            "Invalid node name: must be 1-256 characters using only "
            "alphanumerics, dots, dashes, underscores, colons, and plus signs"
        )
    return node_name


def _safe_filename(node_name):
    """Convert a node name to a safe filename component."""
    # Replace any non-alphanumeric/dash/underscore chars with underscore
    safe = re.sub(r"[^a-zA-Z0-9_-]", "_", node_name)
    # Truncate to avoid exceeding filesystem name limits (255 bytes)
    # _FILE_PREFIX is 12 chars, ".conf" is 5 chars, so allow 238 for the middle
    return safe[:238]


def _config_path(node_name):
    """Return the full path to the WirePlumber config file for a node."""
    filename = f"{_FILE_PREFIX}{_safe_filename(node_name)}.conf"
    return os.path.join(WIREPLUMBER_DIR, filename)


def _escape_spa_json(value):
    """Escape a string value for SPA-JSON (WirePlumber config format).

    Handles backslashes, double quotes, and control characters that could
    break the SPA-JSON structure.
    """
    value = value.replace("\\", "\\\\")
    value = value.replace('"', '\\"')
    # Strip any control characters (newlines, tabs, etc.) that could inject
    # new lines or directives into the config file
    value = re.sub(r"[\x00-\x1f\x7f]", "", value)
    return value


def _safe_write(path, content):
    """Write content to a file safely, refusing to follow symlinks.

    Uses O_NOFOLLOW to prevent symlink attacks when running as root.
    Sets explicit file permissions (0644).
    """
    # Refuse to write if path is a symlink
    if os.path.lexists(path) and os.path.islink(path):
        raise RuntimeError(
            f"Refusing to write to {path}: path is a symlink"
        )

    flags = os.O_WRONLY | os.O_CREAT | os.O_TRUNC
    # O_NOFOLLOW prevents following symlinks on the final path component
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW

    try:
        fd = os.open(path, flags, 0o644)
    except OSError as e:
        raise RuntimeError(f"Cannot open {path}: {e}")

    try:
        os.write(fd, content.encode("utf-8"))
    except OSError as e:
        raise RuntimeError(f"Cannot write to {path}: {e}")
    finally:
        os.close(fd)


def _safe_remove(path):
    """Remove a file safely, refusing to follow symlinks.

    Checks that the path is a regular file (not a symlink or special file)
    before removing, to prevent deleting unintended targets.
    """
    try:
        st = os.lstat(path)
    except FileNotFoundError:
        raise ValueError(f"File not found: {path}")
    except OSError as e:
        raise RuntimeError(f"Cannot stat {path}: {e}")

    if stat.S_ISLNK(st.st_mode):
        raise RuntimeError(f"Refusing to remove {path}: path is a symlink")
    if not stat.S_ISREG(st.st_mode):
        raise RuntimeError(f"Refusing to remove {path}: not a regular file")

    try:
        os.remove(path)
    except OSError as e:
        raise RuntimeError(f"Cannot remove {path}: {e}")


def generate_rule(node_name, new_description):
    """Generate WirePlumber SPA-JSON config content for renaming a node.

    Args:
        node_name: The PipeWire node.name to match (e.g. "alsa_output.usb-...").
        new_description: The new human-readable description.

    Returns:
        The config file content as a string.
    """
    escaped_name = _escape_spa_json(node_name)
    escaped_desc = _escape_spa_json(new_description)
    return (
        f"# Generated by portname — do not edit manually\n"
        f"monitor.alsa.rules = [\n"
        f"  {{\n"
        f'    matches = [ {{ node.name = "{escaped_name}" }} ]\n'
        f"    actions = {{\n"
        f"      update-props = {{\n"
        f'        node.description = "{escaped_desc}"\n'
        f'        node.nick        = "{escaped_desc}"\n'
        f"      }}\n"
        f"    }}\n"
        f"  }}\n"
        f"]\n"
    )


def rename_node(node_name, new_description):
    """Create a WirePlumber rule to rename a USB audio node. Must be run as root."""
    if os.geteuid() != 0:
        raise PermissionError("Must be run as root")

    node_name = validate_node_name(node_name)

    log.info("Creating WirePlumber rename rule for '%s' -> '%s'",
             node_name, new_description)

    os.makedirs(WIREPLUMBER_DIR, exist_ok=True)

    content = generate_rule(node_name, new_description)
    path = _config_path(node_name)

    _safe_write(path, content)

    log.info("WirePlumber rule written to %s", path)


def revert_node(node_name):
    """Remove the WirePlumber rename rule for a USB audio node. Must be run as root."""
    if os.geteuid() != 0:
        raise PermissionError("Must be run as root")

    node_name = validate_node_name(node_name)
    path = _config_path(node_name)
    log.info("Removing WirePlumber rename rule for '%s'", node_name)

    _safe_remove(path)

    log.info("WirePlumber rule removed: %s", path)


def is_node_renamed(node_name):
    """Check if a USB audio node has a portname WirePlumber rename rule."""
    return os.path.exists(_config_path(node_name))


def get_current_description(node_name):
    """Read the current custom description from a WirePlumber rename rule.

    Returns the description string, or None if no rule exists.
    """
    path = _config_path(node_name)
    if not os.path.exists(path):
        return None
    try:
        with open(path) as f:
            for line in f:
                stripped = line.strip()
                if stripped.startswith("node.description"):
                    # Parse: node.description = "My Name"
                    match = re.search(r'"([^"]*)"', stripped)
                    if match:
                        return match.group(1)
    except (OSError, UnicodeDecodeError):
        return None
    return None


def get_all_renamed():
    """Return a list of (node_name, description) for all portname WirePlumber rules."""
    renamed = []
    if not os.path.isdir(WIREPLUMBER_DIR):
        return renamed

    for filename in os.listdir(WIREPLUMBER_DIR):
        if not filename.startswith(_FILE_PREFIX) or not filename.endswith(".conf"):
            continue

        filepath = os.path.join(WIREPLUMBER_DIR, filename)

        # Skip symlinks — only read regular files
        if os.path.islink(filepath):
            log.warning("Skipping symlink: %s", filepath)
            continue

        node_name = None
        description = None
        try:
            with open(filepath) as f:
                for line in f:
                    stripped = line.strip()
                    if "node.name" in stripped:
                        match = re.search(r'node\.name\s*=\s*"([^"]*)"', stripped)
                        if match:
                            node_name = match.group(1)
                    if stripped.startswith("node.description"):
                        match = re.search(r'"([^"]*)"', stripped)
                        if match:
                            description = match.group(1)
        except (OSError, UnicodeDecodeError):
            continue

        if node_name:
            renamed.append((node_name, description or ""))

    return renamed


def revert_all():
    """Remove all portname WirePlumber rename rules. Must be run as root.

    Attempts to revert all rules, continuing past individual failures.
    Returns a list of reverted node names.
    """
    if os.geteuid() != 0:
        raise PermissionError("Must be run as root")

    reverted = []
    errors = []
    for node_name, _desc in get_all_renamed():
        try:
            revert_node(node_name)
            reverted.append(node_name)
        except (ValueError, RuntimeError) as e:
            log.error("Failed to revert USB node '%s': %s", node_name, e)
            errors.append(f"{node_name}: {e}")

    if errors and not reverted:
        raise RuntimeError(
            f"Failed to revert USB renames: {'; '.join(errors)}"
        )
    elif errors:
        log.warning("Some USB reverts failed: %s", "; ".join(errors))

    return reverted
