"""WirePlumber rule generation for renaming USB audio devices/nodes."""

import logging
import os
import re

log = logging.getLogger(__name__)

_DEFAULT_WIREPLUMBER_DIR = "/etc/wireplumber/wireplumber.conf.d"

# Allow override for testing, but ignore when running as root (same pattern as core.py).
if os.geteuid() == 0:
    WIREPLUMBER_DIR = _DEFAULT_WIREPLUMBER_DIR
else:
    WIREPLUMBER_DIR = os.environ.get(
        "PORTNAME_WIREPLUMBER_DIR", _DEFAULT_WIREPLUMBER_DIR
    )

# Prefix for config files created by portname
_FILE_PREFIX = "90-portname-"


def _safe_filename(node_name):
    """Convert a node name to a safe filename component."""
    # Replace any non-alphanumeric/dash/underscore chars with underscore
    return re.sub(r"[^a-zA-Z0-9_-]", "_", node_name)


def _config_path(node_name):
    """Return the full path to the WirePlumber config file for a node."""
    filename = f"{_FILE_PREFIX}{_safe_filename(node_name)}.conf"
    return os.path.join(WIREPLUMBER_DIR, filename)


def _escape_spa_json(value):
    """Escape a string value for SPA-JSON (WirePlumber config format)."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def generate_rule(node_name, new_description):
    """Generate WirePlumber SPA-JSON config content for renaming a node.

    Args:
        node_name: The PipeWire node.name to match (e.g. "alsa_output.usb-...").
        new_description: The new human-readable description.

    Returns:
        The config file content as a string.
    """
    escaped_name = _escape_spa_json(node_name)
    escaped_desc = _escape_spa_json(new_description)
    return (
        f"# Generated by portname — do not edit manually\n"
        f"monitor.alsa.rules = [\n"
        f"  {{\n"
        f'    matches = [ {{ node.name = "{escaped_name}" }} ]\n'
        f"    actions = {{\n"
        f"      update-props = {{\n"
        f'        node.description = "{escaped_desc}"\n'
        f'        node.nick        = "{escaped_desc}"\n'
        f"      }}\n"
        f"    }}\n"
        f"  }}\n"
        f"]\n"
    )


def rename_node(node_name, new_description):
    """Create a WirePlumber rule to rename a USB audio node. Must be run as root."""
    if os.geteuid() != 0:
        raise PermissionError("Must be run as root")

    log.info("Creating WirePlumber rename rule for '%s' -> '%s'",
             node_name, new_description)

    os.makedirs(WIREPLUMBER_DIR, exist_ok=True)

    content = generate_rule(node_name, new_description)
    path = _config_path(node_name)

    try:
        with open(path, "w") as f:
            f.write(content)
    except OSError as e:
        raise RuntimeError(f"Cannot write WirePlumber config {path}: {e}")

    log.info("WirePlumber rule written to %s", path)


def revert_node(node_name):
    """Remove the WirePlumber rename rule for a USB audio node. Must be run as root."""
    if os.geteuid() != 0:
        raise PermissionError("Must be run as root")

    path = _config_path(node_name)
    log.info("Removing WirePlumber rename rule for '%s'", node_name)

    if not os.path.exists(path):
        raise ValueError(f"No rename rule found for node '{node_name}'")

    try:
        os.remove(path)
    except OSError as e:
        raise RuntimeError(f"Cannot remove WirePlumber config {path}: {e}")

    log.info("WirePlumber rule removed: %s", path)


def is_node_renamed(node_name):
    """Check if a USB audio node has a portname WirePlumber rename rule."""
    return os.path.exists(_config_path(node_name))


def get_current_description(node_name):
    """Read the current custom description from a WirePlumber rename rule.

    Returns the description string, or None if no rule exists.
    """
    path = _config_path(node_name)
    if not os.path.exists(path):
        return None
    try:
        with open(path) as f:
            for line in f:
                stripped = line.strip()
                if stripped.startswith("node.description"):
                    # Parse: node.description = "My Name"
                    match = re.search(r'"([^"]*)"', stripped)
                    if match:
                        return match.group(1)
    except (OSError, UnicodeDecodeError):
        return None
    return None


def get_all_renamed():
    """Return a list of (node_name, description) for all portname WirePlumber rules."""
    renamed = []
    if not os.path.isdir(WIREPLUMBER_DIR):
        return renamed

    for filename in os.listdir(WIREPLUMBER_DIR):
        if not filename.startswith(_FILE_PREFIX) or not filename.endswith(".conf"):
            continue

        filepath = os.path.join(WIREPLUMBER_DIR, filename)
        node_name = None
        description = None
        try:
            with open(filepath) as f:
                for line in f:
                    stripped = line.strip()
                    if "node.name" in stripped:
                        match = re.search(r'node\.name\s*=\s*"([^"]*)"', stripped)
                        if match:
                            node_name = match.group(1)
                    if stripped.startswith("node.description"):
                        match = re.search(r'"([^"]*)"', stripped)
                        if match:
                            description = match.group(1)
        except (OSError, UnicodeDecodeError):
            continue

        if node_name:
            renamed.append((node_name, description or ""))

    return renamed


def revert_all():
    """Remove all portname WirePlumber rename rules. Must be run as root.

    Returns a list of reverted node names.
    """
    if os.geteuid() != 0:
        raise PermissionError("Must be run as root")

    reverted = []
    for node_name, _desc in get_all_renamed():
        revert_node(node_name)
        reverted.append(node_name)

    return reverted
